name: Java-CI-CD
run-name: ${{ gitea.actor }} is deploying SpringBoot with JDK 21
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    # 【关键】使用我们手动下载好的本地“工具箱”
    container:
      image: maven:3.9.6-eclipse-temurin-21-alpine

    steps:
      # 第一步：手动拉取代码（不走 GitHub，走内网 Gitea）
      - name: Local Checkout
        run: |
          # 清空当前工作目录并从 Gitea 克隆最新代码
          git clone http://localhost:3000/${GITEA_REPOSITORY}.git .
          git checkout ${GITEA_SHA}

      # 第二步：编译打包（使用镜像内预装的 Maven 和 JDK 21）
      - name: Build JAR
        run: |
          mvn clean package -DskipTests

      # 第三步：构建并运行容器
      # 注意：这要求 Runner 的 docker-compose 必须挂载了 /var/run/docker.sock
      - name: Build and Update Docker Image
        run: |
          docker build -t my-app:latest .
          docker stop my-app-container || true
          docker rm my-app-container || true
          docker run -d --name my-app-container -p 8080:8080 my-app:latest