name: Java-CI-CD
run-name: ${{ gitea.actor }} is deploying SpringBoot
on: [push]

jobs:
  build-and-run:
    # 这里的标签必须对应你在 config.yaml 里改的那个 :host
    runs-on: ubuntu-latest

    steps:
      # 第一步：智能拉取代码
      - name: Checkout Code
        run: |
          # 如果目录不存在，就克隆；如果存在，就拉取最新代码
          if [ -d ".git" ]; then
            git fetch --all
            git reset --hard origin/main
          else
            git clone http://${{ gitea.token }}@192.168.239.129:3000/${{ gitea.repository }}.git .
          fi

      # 第二步：直接调用宿主机编译 (秒开)
      - name: Build JAR
        run: |
          # 此时直接使用你刚才在宿主机 sudo apt install maven 装好的工具
          mvn clean package -DskipTests

      # 第三步：直接调用宿主机 Docker (秒开)
      - name: Build and Run
        run: |
          # 注意：这里删掉了 apt-get install docker.io，因为宿主机自带 Docker
          docker build -t my-app:latest .
          docker stop my-app-container || true
          docker rm my-app-container || true
          docker run -d --name my-app-container -p 8080:8080 my-app:latest