name: Java-CI-CD
run-name: ${{ gitea.actor }} is deploying SpringBoot with JDK 21
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    # 【关键】使用我们手动下载好的本地“工具箱”
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      # 第一步：手动拉取代码（不走 GitHub，走内网 Gitea）
      - name: Local Checkout
        run: |
        # 2. 加入用户名（建议直接写 admin 或你的账号名）和 Token
          git clone http://${{ gitea.token }}@192.168.239.129:3000/${{ gitea.repository }}.git .
        # 切换到触发本次任务的具体提交点
          git checkout ${{ gitea.sha }}

      # 第二步：编译打包（使用镜像内预装的 Maven 和 JDK 21）
      - name: Build JAR
        run: |
          mvn clean package -DskipTests

      # 第三步：构建并运行容器
      # 注意：这要求 Runner 的 docker-compose 必须挂载了 /var/run/docker.sock
      - name: Build and Update Docker Image
        run: |
        # 1. 在 Debian 环境的 Maven 镜像里安装 Docker 客户端
          apt-get update && apt-get install -y docker.io
        # 2. 执行构建（这会通过挂载的 .sock 发送给宿主机执行）
          docker build -t my-app:latest .
          docker stop my-app-container || true
          docker rm my-app-container || true
          docker run -d --name my-app-container -p 8080:8080 my-app:latest