name: Java-CI-CD
run-name: ${{ gitea.actor }} is deploying SpringBoot
on: [push]

jobs:
  build-and-run:
    # 这里的标签必须对应你在 config.yaml 里改的那个 :host
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-21-jammy
    steps:
      # 第一步：智能拉取代码
      - name: Checkout Code
        run: |
          # 如果目录不存在，就克隆；如果存在，就拉取最新代码
          if [ -d ".git" ]; then
            git fetch --all
            git reset --hard origin/main
          else
            git clone http://${{ gitea.token }}@192.168.239.129:3000/${{ gitea.repository }}.git .
          fi

      # 第二步：直接调用宿主机编译 (秒开)
      - name: Build JAR
        run: |
          # 此时直接使用你刚才在宿主机 sudo apt install maven 装好的工具
          mvn clean package -DskipTests -Dmaven.repo.local=/root/.m2/repository

      # 第三步：直接调用宿主机 Docker (秒开)
      - name: Build and Run
        run: |
          # 换源加速 (解决 apt-get 卡顿)
          sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
          sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
          # 自动安装 Docker 客户端（这比手动挂载宿主机文件稳得多）
          apt-get update && apt-get install -y docker.io
          
          # 检查一下
          docker --version
          # 停止旧容器并清理（使用 -f 强制删除更简洁）
          docker rm -f my-app-container || true
          # 显式指定在当前目录构建
          docker build -t my-app:latest .
          
          # 启动新容器
          docker run -d --name my-app-container -p 8080:8080 my-app:latest
          docker image prune -f