name: Java-CI-CD
run-name: ${{ github.actor }} is deploying SpringBoot with JDK 21
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # 这是一个高性能、稳定的 JDK 发行版
          cache: maven            # 开启缓存，下次编译会快很多

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build and Update Docker Image
        run: |
          docker build -t my-app:latest .
          docker stop my-app-container || true
          docker rm my-app-container || true
          docker run -d --name my-app-container -p 8080:8080 my-app:latest